#cloud:
#  aws:
#    credentials:
#      accessKey: 
#      secretKey: 
#    s3:
#      bucket:
#        url: https://s3.ap-northeast-2.amazonaws.com/miniproject-coffeebara
#        nodeValue: miniproject-coffeebara
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: 'false'
#
spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
  h2:
    console:
      enabled: 'true'
  datasource:
    username: beomsoo
    url: jdbc:h2:mem:1000store
    password: 1234
