spring:
  h2:
    console:
      enabled: true
#  profiles:
#    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cloneprojectdb
    username: sa
    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://springboot-database.chh8aypxdyul.ap-northeast-2.rds.amazonaws.com:3306/hanghaeblog
#    username: admin
#    password: 1tjddls4

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: bottlecofffin@gmail.com
    password: pwcewokizdewtfnv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

cloud:
  aws:
    credentials:
      accessKey: AKIASJEGVRVUVZ3XDAUE
      secretKey: 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
#    s3:
#      bucket:
#        url: https://s3.ap-northeast-2.amazonaws.com/miniproject-coffeebara
#        nodeValue: miniproject-coffeebara
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'